"""Init

Revision ID: 70d8880272c2
Revises: 
Create Date: 2026-01-08 10:59:55.942933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70d8880272c2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sightseeings', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('sightseeings', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sightseeings', 'image_url')
    op.drop_column('sightseeings', 'created_at')
    # ### end Alembic commands ###
