"""add location column to sightseeings

Revision ID: da3d4bb101db
Revises: 08d4f9b96b7b
Create Date: 2025-08-12 14:18:17.010799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da3d4bb101db'
down_revision: Union[str, Sequence[str], None] = '08d4f9b96b7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sightseeings', sa.Column('location', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sightseeings', 'location')
    # ### end Alembic commands ###
